### ISSUE TITLE
What is the difference between CrimeScape and CivicScape?

### ISSUE THREAD

**Issue by dkg** [CivicScape/CivicScape#4]
The repo is named CivicScape, and it describes the project.  But some parts of the repo refer to CrimeScape, without distinguishing it clearly from CivicScape.  Is it the same thing, just renamed?  if so, please complete the rename :)  If it's different, can you clarify the distinction before introducing CrimeScape?

**Comment by sparker6** [comment]
ty! clarified.

**Comment by dkg** [comment]
looks like it was clarified in 2b4745c6fc4bee4850556f2176ffc1b85449bb9f -- is that right?
